name: 'Helm Publish'
description: 'Build and deploy your Helm charts to GitHub Pages.'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  access-token:
    description: 'A personal access token needed to push your site after it has been built.'
    required: true
  deploy-branch:
    description: 'The branch expected by GitHub to have the static files needed for your site.'
    required: false
    default: 'master'
  charts-folder:
    description: 'The folder in which the helm charts are located'
    required: false
    default: 'charts'
runs:
  using: 'node12'
  main: 'index.js'
